name: rebalance
description: Portfolio rebalancing and asset allocation tracking - private, offline, and fast.
publish_to: 'none'
version: 1.0.3+12

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Storage & Encryption
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^12.1.3
  
  # Formatting & Internationalization
  intl: ^0.18.1
  
  # Charts & Visualization
  fl_chart: ^0.65.0
  
  # In-App Purchases
  in_app_purchase: ^3.1.11
  
  # Device & App Info
  package_info_plus: ^4.2.0
  
  # External Links
  url_launcher: ^6.2.1
  
  # Notifications
  # flutter_local_notifications: ^16.3.0
  
  # Biometrics
  # local_auth: ^2.1.7
  
  # File Handling
  path_provider: ^2.1.1
  csv: ^5.0.2
  share_plus: ^7.2.1
  permission_handler: ^11.1.0
  
  # Cryptography
  crypto: ^3.0.3
  
  # Material Design
  material_color_utilities: 0.11.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  golden_toolkit: ^0.15.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/screenshots/

# App launcher icon configuration
flutter_launcher_icons:
  android: true
  ios: false  # Set to true when you have iOS setup
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#1a1a1a"  # Dark background for adaptive icon
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  
# Splash screen configuration  
flutter_native_splash:
  color: "#3C4043"  # Charcoal gray matching your icon
  image: "assets/icons/splash_icon.png"
  android: true
  ios: false
  android_12:
    color: "#3C4043"
    image: "assets/icons/splash_icon.png"
  android_gravity: center
  fullscreen: true